services:
  crm-api:
    image: imashiksarkar/crm-api:v1.0.1
    container_name: crm-api
    ports:
      - '3000:3000'
    environment:
      DB_URL: postgres://produser:prodpassword@postgres-prod:5432/minicrm
      PORT: 3000
      JWT_SECRET: secret
      ACC_TOKEN_EXP: 300000 # 5 minutes
      REF_TOKEN_EXP: 86400000 # 1 day
    depends_on:
      - postgres-prod
    restart: always

  postgres-prod:
    image: postgres:16.8-alpine
    container_name: postgres-prod
    environment:
      POSTGRES_USER: produser
      POSTGRES_PASSWORD: prodpassword
      POSTGRES_DB: minicrm
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - crm-data:/var/lib/postgresql/data

  postgres-test:
    image: postgres:16.8-alpine
    container_name: postgres-test
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: minicrm
    tmpfs:
      - /var/lib/postgresql/data:rw
    command:
      [
        'postgres',
        '-c',
        'fsync=off',
        '-c',
        'full_page_writes=off',
        '-c',
        'synchronous_commit=off',
      ]
    restart: 'no'

volumes:
  crm-data:
